### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by aous72** [seannz/cogl#3]
Hi Sean, 

I think it is useful to mention hardware requirements in the README file.  Something like:

You need a machine that supports AVX.  For Intel, this means 2nd gen Core machine (Sandy Bridge) or later; that is, a chip model starting with 2 or more, such as i5-2500 all the way to the latest i9-9900K, should be fine.  The 2nd gen core machines first appeared in 2010-2011 (i.e., quite old).  Machine bought after that should be fine. 

Cheers,
Aous.

**Comment by seannz** [comment]
Done! Basically copy-pasted your comment into the README.

**Comment by aous72** [comment]
Excellent!
